// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Classe
 */
export type Classe = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * School Id
     */
    school_id: string;
};

/**
 * ClasseCreate
 */
export type ClasseCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * ClassePublic
 */
export type ClassePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Id
     */
    id: string;
    /**
     * School Id
     */
    school_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    ecole: School;
};

/**
 * ClasseUpdate
 */
export type ClasseUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
};

/**
 * ClassesPublic
 */
export type ClassesPublic = {
    /**
     * Data
     */
    data: Array<ClassePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * School
 */
export type School = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Academie
     */
    academie?: string;
    /**
     * Ief
     */
    ief?: string;
    /**
     * Directeur
     */
    directeur?: string | null;
    /**
     * Adresse
     */
    adresse?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Responsable Id
     */
    responsable_id: string;
};

/**
 * SchoolCreate
 */
export type SchoolCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Academie
     */
    academie?: string;
    /**
     * Ief
     */
    ief?: string;
    /**
     * Directeur
     */
    directeur?: string | null;
    /**
     * Adresse
     */
    adresse?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
};

/**
 * SchoolPublic
 */
export type SchoolPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Academie
     */
    academie?: string;
    /**
     * Ief
     */
    ief?: string;
    /**
     * Directeur
     */
    directeur?: string | null;
    /**
     * Adresse
     */
    adresse?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Responsable Id
     */
    responsable_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * SchoolUpdate
 */
export type SchoolUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Academie
     */
    academie?: string | null;
    /**
     * Ief
     */
    ief?: string | null;
    /**
     * Directeur
     */
    directeur?: string | null;
    /**
     * Adresse
     */
    adresse?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
};

/**
 * SchoolsPublic
 */
export type SchoolsPublic = {
    /**
     * Data
     */
    data: Array<SchoolPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * StudentCreate
 */
export type StudentCreate = {
    /**
     * Ien
     */
    ien: string;
    /**
     * Prenom
     */
    prenom: string;
    /**
     * Nom
     */
    nom: string;
    /**
     * Datnais
     */
    datnais?: string;
    /**
     * Lieunais
     */
    lieunais?: string;
    /**
     * Sexe
     */
    sexe?: string;
    /**
     * Pere
     */
    pere?: string | null;
    /**
     * Mere
     */
    mere?: string | null;
    /**
     * Adresse
     */
    adresse?: string | null;
    /**
     * Contact
     */
    contact?: string | null;
};

/**
 * StudentPublic
 */
export type StudentPublic = {
    /**
     * Ien
     */
    ien: string;
    /**
     * Prenom
     */
    prenom: string;
    /**
     * Nom
     */
    nom: string;
    /**
     * Datnais
     */
    datnais?: string;
    /**
     * Lieunais
     */
    lieunais?: string;
    /**
     * Sexe
     */
    sexe?: string;
    /**
     * Pere
     */
    pere?: string | null;
    /**
     * Mere
     */
    mere?: string | null;
    /**
     * Adresse
     */
    adresse?: string | null;
    /**
     * Contact
     */
    contact?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Classe Id
     */
    classe_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    classe: Classe;
};

/**
 * StudentUpdate
 */
export type StudentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Prenom
     */
    prenom?: string | null;
    /**
     * Nom
     */
    nom?: string | null;
    /**
     * Datnais
     */
    datnais: string | null;
    /**
     * Lieunais
     */
    lieunais?: string | null;
    /**
     * Sexe
     */
    sexe?: string | null;
    /**
     * Pere
     */
    pere?: string | null;
    /**
     * Mere
     */
    mere?: string | null;
    /**
     * Adresse
     */
    adresse?: string | null;
    /**
     * Contact
     */
    contact?: string | null;
};

/**
 * StudentsPublic
 */
export type StudentsPublic = {
    /**
     * Count
     */
    count: number;
    /**
     * Data
     */
    data: Array<StudentPublic>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type schoolsReadSchoolsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/schools/';
};

export type schoolsReadSchoolsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type schoolsReadSchoolsError = schoolsReadSchoolsErrors[keyof schoolsReadSchoolsErrors];

export type schoolsReadSchoolsResponses = {
    /**
     * Successful Response
     */
    200: SchoolsPublic;
};

export type schoolsReadSchoolsResponse = schoolsReadSchoolsResponses[keyof schoolsReadSchoolsResponses];

export type schoolsCreateSchoolData = {
    body: SchoolCreate;
    path?: never;
    query?: never;
    url: '/api/v1/schools/';
};

export type schoolsCreateSchoolErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type schoolsCreateSchoolError = schoolsCreateSchoolErrors[keyof schoolsCreateSchoolErrors];

export type schoolsCreateSchoolResponses = {
    /**
     * Successful Response
     */
    200: SchoolPublic;
};

export type schoolsCreateSchoolResponse = schoolsCreateSchoolResponses[keyof schoolsCreateSchoolResponses];

export type schoolsDeleteSchoolData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/schools/{id}';
};

export type schoolsDeleteSchoolErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type schoolsDeleteSchoolError = schoolsDeleteSchoolErrors[keyof schoolsDeleteSchoolErrors];

export type schoolsDeleteSchoolResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type schoolsDeleteSchoolResponse = schoolsDeleteSchoolResponses[keyof schoolsDeleteSchoolResponses];

export type schoolsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/schools/{id}';
};

export type schoolsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type schoolsReadItemError = schoolsReadItemErrors[keyof schoolsReadItemErrors];

export type schoolsReadItemResponses = {
    /**
     * Successful Response
     */
    200: SchoolPublic;
};

export type schoolsReadItemResponse = schoolsReadItemResponses[keyof schoolsReadItemResponses];

export type schoolsUpdateSchoolData = {
    body: SchoolUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/schools/{id}';
};

export type schoolsUpdateSchoolErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type schoolsUpdateSchoolError = schoolsUpdateSchoolErrors[keyof schoolsUpdateSchoolErrors];

export type schoolsUpdateSchoolResponses = {
    /**
     * Successful Response
     */
    200: SchoolPublic;
};

export type schoolsUpdateSchoolResponse = schoolsUpdateSchoolResponses[keyof schoolsUpdateSchoolResponses];

export type classesReadClassesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/classes/';
};

export type classesReadClassesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type classesReadClassesError = classesReadClassesErrors[keyof classesReadClassesErrors];

export type classesReadClassesResponses = {
    /**
     * Successful Response
     */
    200: ClassesPublic;
};

export type classesReadClassesResponse = classesReadClassesResponses[keyof classesReadClassesResponses];

export type classesCreateClasseData = {
    body: ClasseCreate;
    path?: never;
    query: {
        /**
         * School Id
         */
        school_id: string;
    };
    url: '/api/v1/classes/';
};

export type classesCreateClasseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type classesCreateClasseError = classesCreateClasseErrors[keyof classesCreateClasseErrors];

export type classesCreateClasseResponses = {
    /**
     * Successful Response
     */
    200: ClassePublic;
};

export type classesCreateClasseResponse = classesCreateClasseResponses[keyof classesCreateClasseResponses];

export type classesDeleteClasseData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/classes/{id}';
};

export type classesDeleteClasseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type classesDeleteClasseError = classesDeleteClasseErrors[keyof classesDeleteClasseErrors];

export type classesDeleteClasseResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type classesDeleteClasseResponse = classesDeleteClasseResponses[keyof classesDeleteClasseResponses];

export type classesReadClasseData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/classes/{id}';
};

export type classesReadClasseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type classesReadClasseError = classesReadClasseErrors[keyof classesReadClasseErrors];

export type classesReadClasseResponses = {
    /**
     * Successful Response
     */
    200: ClassePublic;
};

export type classesReadClasseResponse = classesReadClasseResponses[keyof classesReadClasseResponses];

export type classesUpdateClasseData = {
    body: ClasseUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/classes/{id}';
};

export type classesUpdateClasseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type classesUpdateClasseError = classesUpdateClasseErrors[keyof classesUpdateClasseErrors];

export type classesUpdateClasseResponses = {
    /**
     * Successful Response
     */
    200: ClassePublic;
};

export type classesUpdateClasseResponse = classesUpdateClasseResponses[keyof classesUpdateClasseResponses];

export type studentsReadStudentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/students/';
};

export type studentsReadStudentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type studentsReadStudentsError = studentsReadStudentsErrors[keyof studentsReadStudentsErrors];

export type studentsReadStudentsResponses = {
    /**
     * Successful Response
     */
    200: StudentsPublic;
};

export type studentsReadStudentsResponse = studentsReadStudentsResponses[keyof studentsReadStudentsResponses];

export type studentsCreateStudentData = {
    body: StudentCreate;
    path?: never;
    query: {
        /**
         * Classe Id
         */
        classe_id: string;
    };
    url: '/api/v1/students/';
};

export type studentsCreateStudentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type studentsCreateStudentError = studentsCreateStudentErrors[keyof studentsCreateStudentErrors];

export type studentsCreateStudentResponses = {
    /**
     * Successful Response
     */
    200: StudentPublic;
};

export type studentsCreateStudentResponse = studentsCreateStudentResponses[keyof studentsCreateStudentResponses];

export type studentsDeleteStudentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/students/{id}';
};

export type studentsDeleteStudentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type studentsDeleteStudentError = studentsDeleteStudentErrors[keyof studentsDeleteStudentErrors];

export type studentsDeleteStudentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type studentsDeleteStudentResponse = studentsDeleteStudentResponses[keyof studentsDeleteStudentResponses];

export type studentsReadStudentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/students/{id}';
};

export type studentsReadStudentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type studentsReadStudentError = studentsReadStudentErrors[keyof studentsReadStudentErrors];

export type studentsReadStudentResponses = {
    /**
     * Successful Response
     */
    200: StudentPublic;
};

export type studentsReadStudentResponse = studentsReadStudentResponses[keyof studentsReadStudentResponses];

export type studentsUpdateStudentData = {
    body: StudentUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/students/{id}';
};

export type studentsUpdateStudentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type studentsUpdateStudentError = studentsUpdateStudentErrors[keyof studentsUpdateStudentErrors];

export type studentsUpdateStudentResponses = {
    /**
     * Successful Response
     */
    200: StudentPublic;
};

export type studentsUpdateStudentResponse = studentsUpdateStudentResponses[keyof studentsUpdateStudentResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
