"""empty message

Revision ID: 28d1b7431628
Revises: d552be2bea13
Create Date: 2026-09-29 21:38:05.958852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28d1b7431628'
down_revision = 'd552be2bea13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'datnais',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'datnais',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
