"""Add School model

Revision ID: bc061b1ae88d
Revises: fe56fa70289e
Create Date: 2026-09-28 14:49:04.743613

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc061b1ae88d'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('academie', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ief', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('directeur', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('adresse', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=21), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsable_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    # ### end Alembic commands ###
