"""Add Student  model

Revision ID: d552be2bea13
Revises: 0355992d41af
Create Date: 2026-09-29 20:46:18.417388

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd552be2bea13'
down_revision = '0355992d41af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('ien', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('datnais', sa.DateTime(), nullable=True),
    sa.Column('lieunais', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sexe', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('pere', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('mere', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('adresse', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classe_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
