"""empty message

Revision ID: f21dfe1c16eb
Revises: 39e0d2ac5d59
Create Date: 2026-10-01 09:01:55.792943

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f21dfe1c16eb'
down_revision = '39e0d2ac5d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'slug')
    # ### end Alembic commands ###
